### ISSUE TITLE
Default game catalog

### ISSUE THREAD

**Issue by SebeeDev** [Elendan/launcher-bug-report#7]
**Suggestion**
Default install catalog should be placed inside launcher catalog.

**Explanation**
During installation user is able to choose launcher path between *only for current user* and *for all users*.
So making game path default to user catalog even if user chose *for all users* option is bad in this case.

**Screenshot**
![image](https://user-images.githubusercontent.com/3252406/113589849-2ba99f80-9632-11eb-95c3-41b0d9a06355.png)
![image](https://user-images.githubusercontent.com/3252406/113589384-960e1000-9631-11eb-8b0f-ce4cef5b2c81.png)

**Comment by Azword** [comment]
It's corrected now, thx for the nice UX feedback ! I'll let you try the new full flow of installation
